# Generated by Django 3.2.9 on 2021-12-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='collection',
            field=models.CharField(default='test', max_length=10000),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='forsale',
            field=models.CharField(default='test', max_length=10000),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='wantlist',
            field=models.CharField(default='test', max_length=10000),
        ),
    ]
