# Generated by Django 3.2.9 on 2021-12-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0003_auto_20211220_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='collection',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='forsale',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='wantlist',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
